In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
poids = pd.Series(
    [3, 7, 12]
)
poids

0     3
1     7
2    12
dtype: int64

In [4]:
animal = pd.Series(
  ['chat', 'chien', 'koala']
)
animal
animal.astype("category")
#animal.astype(str)

0     chat
1    chien
2    koala
dtype: category
Categories (3, str): ['chat', 'chien', 'koala']

In [5]:
animaux = pd.DataFrame(
  zip(animal, poids),
  columns = ['animal','poids']
)
animaux

  animal  poids
0   chat      3
1  chien      7
2  koala     12

In [13]:
url = "https://koumoul.com/s/data-fair/api/v1/datasets/igt-pouvoir-de-rechauffement-global/convert"
donnees=pd.read_csv(url)

donnees.head(5)
donnees.tail(10)
donnees.sample(15)

donnees.sample(frac=0.05, replace=False) #tirage aléatoire de 5% des données, sans remise

donnees10prem=donnees.head(10)
print(donnees10prem)
donnees10prem.sample(n=100, replace =True)

  INSEE commune                  Commune  Agriculture  Autres transports  \
0         01001  L'ABERGEMENT-CLEMENCIAT  3711.425991                NaN
1         01002    L'ABERGEMENT-DE-VAREY   475.330205                NaN
2         01004        AMBERIEU-EN-BUGEY   499.043526         212.577908
3         01005      AMBERIEUX-EN-DOMBES  1859.160954                NaN
4         01006                  AMBLEON   448.966808                NaN
5         01007                 AMBRONAY  4390.996698         132.968268
6         01008                 AMBUTRIX   489.648726          60.233517
7         01009         ANDERT-ET-CONDON   676.468367                NaN
8         01010                ANGLEFORT  1070.411510         143.815664
9         01011                 APREMONT  2010.790441                NaN

   Autres transports international  CO2 biomasse hors-total      Déchets  \
0                              NaN               432.751835   101.430476
1                              NaN               140.741660   140.675439
2                              NaN             10313.446515  5314.314445
3                              NaN              1144.429311   216.217508
4                              NaN                77.033834    48.401549
5                              NaN              3067.245459  6144.186081
6                              NaN               558.055709    98.388885
7                              NaN               207.181968   149.767083
8                              NaN              1286.621447   146.525382
9                              NaN               249.086914    52.103791

      Energie  Industrie hors-énergie   Résidentiel       Routier  \
0    2.354558                6.911213    309.358195    793.156501
1    2.354558                6.911213    104.866444    348.997893
2  998.332482             2930.354461  16616.822534  15642.420313
3   94.182310              276.448534    663.683146   1756.341319
4         NaN                     NaN     43.714019    398.786800
5  122.437003              359.383094   1898.638273  22481.123575
6    2.354558                6.911213    495.393592   3616.168396
7    2.354558                6.911213    141.533662    696.956038
8  341.410872           175185.892467    448.518801   3199.808360
9    2.354558                6.911213    151.844891    686.153720

      Tertiaire
0    367.036172
1    112.934207
2  10732.376934
3    782.404357
4     51.681756
5   2789.133106
6    356.029873
7    161.266219
8   1206.147643
9    188.542701

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207
6,01008,AMBUTRIX,489.648726,60.233517,NaN,558.055709,98.388885,2.354558,6.911213,495.393592,3616.168396,356.029873
9,01011,APREMONT,2010.790441,NaN,NaN,249.086914,52.103791,2.354558,6.911213,151.844891,686.153720,188.542701
3,01005,AMBERIEUX-EN-DOMBES,1859.160954,NaN,NaN,1144.429311,216.217508,94.182310,276.448534,663.683146,1756.341319,782.404357
7,01009,ANDERT-ET-CONDON,676.468367,NaN,NaN,207.181968,149.767083,2.354558,6.911213,141.533662,696.956038,161.266219
...,...,...,...,...,...,...,...,...,...,...,...,...
5,01007,AMBRONAY,4390.996698,132.968268,NaN,3067.245459,6144.186081,122.437003,359.383094,1898.638273,22481.123575,2789.133106
5,01007,AMBRONAY,4390.996698,132.968268,NaN,3067.245459,6144.186081,122.437003,359.383094,1898.638273,22481.123575,2789.133106
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207
5,01007,AMBRONAY,4390.996698,132.968268,NaN,3067.245459,6144.186081,122.437003,359.383094,1898.638273,22481.123575,2789.133106

In [ ]:
donnees6=donnees.head(6)
poids =[0.5]+[0.5/5]*5
donnees6.sample(n=100, replace=True,weights=poids)

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
...,...,...,...,...,...,...,...,...,...,...,...,...
4,01006,AMBLEON,448.966808,NaN,NaN,77.033834,48.401549,NaN,NaN,43.714019,398.786800,51.681756
2,01004,AMBERIEU-EN-BUGEY,499.043526,212.577908,NaN,10313.446515,5314.314445,998.332482,2930.354461,16616.822534,15642.420313,10732.376934
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
5,01007,AMBRONAY,4390.996698,132.968268,NaN,3067.245459,6144.186081,122.437003,359.383094,1898.638273,22481.123575,2789.133106
5,01007,AMBRONAY,4390.996698,132.968268,NaN,3067.245459,6144.186081,122.437003,359.383094,1898.638273,22481.123575,2789.133106

In [ ]:
donnees['dep'] = donnees['INSEE commune'].str[:2]#on crée une nouvellecolonne dep qui correspond au 2 premier chiffres du code insee commune
donnees.head(3)

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire,dep
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172,01
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207,01
2,01004,AMBERIEU-EN-BUGEY,499.043526,212.577908,NaN,10313.446515,5314.314445,998.332482,2930.354461,16616.822534,15642.420313,10732.376934,01

In [18]:
vars = ['Agriculture', 'Déchets', 'Energie']

donnees[[v + "_log" for v in vars]] = np.log(donnees.loc[:, vars])
donnees.head(3)

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire,dep,Agriculture_log,Déchets_log,Energie_log
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172,01,8.219171,4.619374,0.856353
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207,01,6.164010,4.946455,0.856353
2,01004,AMBERIEU-EN-BUGEY,499.043526,212.577908,NaN,10313.446515,5314.314445,998.332482,2930.354461,16616.822534,15642.420313,10732.376934,01,6.212693,8.578159,6.906086

In [22]:
import pandas as pd

emissions = pd.read_csv("https://koumoul.com/s/data-fair/api/v1/datasets/igt-pouvoir-de-rechauffement-global/convert")
emissions.head(2)

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207

In [23]:
emissions_copy=emissions.loc[:,["INSEE commune", "Commune", "Autres transports", "Autres transports international"]]
print(emissions_copy)

emissions_copy=emissions_copy.rename(columns={"INSEE commune": "code_insee", "Autres transports": "transports", "Autres transports international":"transport_international"})

emissions_copy=emissions_copy.fillna(0)
#emissions_copy["dep"]=emissions_copy["code_insee"].str[:2]

      INSEE commune                  Commune  Autres transports  \
0             01001  L'ABERGEMENT-CLEMENCIAT                NaN
1             01002    L'ABERGEMENT-DE-VAREY                NaN
2             01004        AMBERIEU-EN-BUGEY         212.577908
3             01005      AMBERIEUX-EN-DOMBES                NaN
4             01006                  AMBLEON                NaN
...             ...                      ...                ...
35793         95676       VILLERS-EN-ARTHIES                NaN
35794         95678            VILLIERS-ADAM                NaN
35795         95680          VILLIERS-LE-BEL                NaN
35796         95682          VILLIERS-LE-SEC                NaN
35797         95690      WY-DIT-JOLI-VILLAGE                NaN

       Autres transports international
0                                  NaN
1                                  NaN
2                                  NaN
3                                  NaN
4                                  NaN
...                                ...
35793                              NaN
35794                              NaN
35795                              NaN
35796                              NaN
35797                              NaN

[35798 rows x 4 columns]

In [24]:
emissions_copy["dep"]=emissions_copy["code_insee"].str[:2]
emissions_copy["transports_total"]=emissions_copy["transports"]+emissions_copy["transport_international"]
emissions_copy.head(5)

,code_insee,Commune,transports,transport_international,dep,transports_total
0,01001,L'ABERGEMENT-CLEMENCIAT,0.000000,0.0,01,0.000000
1,01002,L'ABERGEMENT-DE-VAREY,0.000000,0.0,01,0.000000
2,01004,AMBERIEU-EN-BUGEY,212.577908,0.0,01,212.577908
3,01005,AMBERIEUX-EN-DOMBES,0.000000,0.0,01,0.000000
4,01006,AMBLEON,0.000000,0.0,01,0.000000

In [36]:
emissions_copy_tri=emissions_copy.sort_values(by="transports_total", ascending=False)

emissions_copy_sum=emissions_copy.groupby(by="dep")["transports_total"].sum().reset_index(name="transports_total_par_dep")
emissions_copy_sum.head(10)
emissions_copy_sum_tri =emissions_copy_sum.sort_values(by="transports_total_par_dep", ascending=False)
emissions_copy_sum_tri.head(10)

   dep  transports_total_par_dep
77  77              9.231533e+06
76  76              2.972445e+06
91  91              2.097139e+06
12  13              1.314893e+06
5   06              1.235532e+06
69  69              1.165837e+06
93  93              1.161017e+06
95  95              1.160899e+06
59  59              1.027594e+06
68  68              6.918383e+05

In [51]:
emissions_copy_select = emissions_copy.loc[emissions_copy["dep"].isin(["13", "31"])]
emissions_copy_select.head(10)

emissions_copy_select_tri=emissions_copy_select.sort_values(by="transports_total", ascending=False)
emissions_copy_select_tri.head(10)

,code_insee,Commune,transports,transport_international,dep,transports_total
4397,13054,MARIGNANE,245375.418650,527360.799265,13,772736.217915
11684,31069,BLAGNAC,210157.688544,403717.366279,31,613875.054823
4438,13096,SAINTES-MARIES-DE-LA-MER,271182.758578,0.000000,13,271182.758578
4347,13004,ARLES,148752.651229,569.110507,13,149321.761736
4398,13056,MARTIGUES,2712.749275,30434.762405,13,33147.511680
4420,13078,PORT-SAINT-LOUIS-DU-RHONE,3786.145492,22370.580019,13,26156.725511
4382,13039,FOS-SUR-MER,1893.383189,17227.234585,13,19120.617773
4470,13209,MARSEILLE-9E-ARRONDISSEMENT,206.323957,15168.902916,13,15375.226873
4369,13026,CHATEAUNEUF-LES-MARTIGUES,7320.451717,59.318285,13,7379.770002
4419,13077,PORT-DE-BOUC,522.306870,5332.487885,13,5854.794756